from random import randint
from time import sleep
itens = ('Pedra', 'Papel', 'Tesoura')
pc = randint(0,  2 )
print('Suas opções:')
print('[ 0 ] PEDRA')
print('[ 1 ] PAPEL')
print('[ 3 ] TESOURA')
jogada = int(input('Qual é a sua jogada? '))
print('Pedra')
sleep(1)
print('Papel')
sleep(1)
print('Tesoooou...')
sleep(2)
print('Ra!')
print('-=-=-=-=-=-=-=-=-=-=-=-=-=')
if jogada == 0 and pc == 0:
    print('Computador jogou Pedra')
    print('Jogador jogou Pedra')
    print('-=-=-=-=-=-=-=-=-=-=-=-=-=')
    print('\033[1:33mEMPATE\033[m')
elif jogada == 0 and pc == 1:
    print('Computador jogou Papel')
    print('Jogador jogou Pedra')
    print('-=-=-=-=-=-=-=-=-=-=-=-=-=')
    print('\033[1:31mJOGADOR PERDEU!\033[m')
elif jogada == 0 and pc == 2:
    print('Computador jogou Tesoura')
    print('Jogador jogou Pedra')
    print('-=-=-=-=-=-=-=-=-=-=-=-=-=')
    print('\033[1:32mJOGADOR VENCEU!\033[m')
elif jogada == 1 and pc == 0:
    print('Computador jogou Pedra')
    print('Jogador jogou Papel')
    print('-=-=-=-=-=-=-=-=-=-=-=-=-=')
    print('\033[1:32mJOGADOR VENCEU!\033[m')
elif jogada == 1 and pc == 1:
    print('Computador jogou Pedra')
    print('Jogador jogou Papel')
    print('-=-=-=-=-=-=-=-=-=-=-=-=-=')
    print('\033[1:33mEMPATE!\033[m')
elif jogada == 1 and pc == 2:
    print('Computador jogou Tesoura')
    print('Jogador jogou Papel')
    print('-=-=-=-=-=-=-=-=-=-=-=-=-=')
    print('\033[1:31mJOGADOR PERDEU!\033[m')
elif jogada == 2 and pc == 0:
    print('Computador jogou Pedra')
    print('Jogador jogou Tesoura')
    print('-=-=-=-=-=-=-=-=-=-=-=-=-=')
    print('\033[1:31mJOGADOR PERDEU!\033[m')
elif jogada == 2 and pc == 1:
    print('Computador jogou Papel')
    print('Jogador jogou Tesoura')
    print('-=-=-=-=-=-=-=-=-=-=-=-=-=')
    print('\033[1:32mJOGADOR VENCEU!\033[m')
elif jogada == 2 and pc == 2:
    print('Computador jogou Pedra')
    print('Jogador jogou Tesoura')
    print('-=-=-=-=-=-=-=-=-=-=-=-=-=')
    print('\033[1:33mEMPATE!\033[m')